apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-temp
  name: nifi-temp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-scripts
  name: nifi-scripts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-lib
  name: nifi-lib
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-logs
  name: nifi-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-data
  name: nifi-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-flowfile
  name: nifi-flowfile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-conf
  name: nifi-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-content
  name: nifi-content
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-upload
  name: nifi-upload
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-provenance
  name: nifi-provenance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-database
  name: nifi-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-extensions
  name: nifi-extensions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nifi-keytool
  name: nifi-keytool
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#   volumeName: pvc-e2f3d668-5af7-4ee6-a374-dab517458829
status: {}
---

